services:
  ### TRAEFIK ##############################################
  traefik:
    container_name: global-traefik
    build:
      context: ./.docker/traefik
      dockerfile: Dockerfile
    restart: unless-stopped
    command: --providers.docker=true
    volumes:
      - ./.docker/traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./.docker/traefik/tls.yml:/etc/traefik/tls.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik:/data
      - ./.docker/traefik/certs:/etc/ssl/traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "8082:8082"
    labels:
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.GLOBAL_TRAEFIK.rule=Host(`traefik.local`)"
      - "traefik.http.routers.GLOBAL_TRAEFIK.tls=true"
    networks:
      - global-traefik

networks:
  global-traefik:
    name: global-traefik
    external: true
volumes:
  traefik:
    driver: local
