#!/bin/sh

SHELL_ACTIVE="${HOME}/.$(basename $SHELL)rc"

cd ~

rm -rf .GlobalTraefik

cat $SHELL_ACTIVE | grep -v ".GlobalTraefik/globaltraefikrc.sh" > "${SHELL_ACTIVE}_tmp"
mv "${SHELL_ACTIVE}_tmp" $SHELL_ACTIVE

cd - > /dev/null 2> /dev/null
