tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/ssl/traefik/traefik.crt
        keyFile: /etc/ssl/traefik/traefik.pem
  certificates:
    - certFile: /etc/ssl/traefik/traefik.crt
      keyFile: /etc/ssl/traefik/traefik.pem
